export const USER_INFO = 'USER_INFO'
export const SHOW_BOTTOM_BAR = 'SHOW_BOTTOM_BAR'
export const SEAT_SELECTION = 'SEAT_SELECTION'
export const DEL_SEAT = 'DEL_SEAT'
export const CLEAR_SELECTION = 'CLEAR_SELECTION'
export const EXTEND_SEAT = 'EXTEND_SEAT'
export const PAY_DIALOG_TRIGER = 'PAY_DIALOG_TRIGER'
export const CHECK_OUT_COUPON = 'CHECK_OUT_COUPON'
export const SHOW_MORE_TICKET = 'SHOW_MORE_TICKET'
export const SHOW_DATE_PICKER = 'SHOW_DATE_PICKER'
export const SAVE_FILM_DATA = 'SAVE_FILM_DATA'
export const MORE_TICKETS_TRIGER = 'MORE_TICKETS_TRIGER'
export const MORE_PAY_TRIGER = 'MORE_PAY_TRIGER'
export const SHOW_FULL_ORDER = 'SHOW_FULL_ORDER'
export const SHOW_REPLACE_GOODS = 'SHOW_REPLACE_GOODS'
export const SAVE_ALL_PAY = 'SAVE_ALL_PAY'
export const SHOW_MORE_NAV = 'SHOW_MORE_NAV'
export const SAVE_TIME_DATA = 'SAVE_TIME_DATA'
export const SAVE_HALL_DATA = 'SAVE_HALL_DATA'
export const SET_FILM_CURRENT_SEL = 'SET_FILM_CURRENT_SEL'
export const SET_MOVIE_ID = 'SET_MOVIE_ID'
export const SET_FILM_CONTENTS = 'SET_FILM_CONTENTS'
export const SET_HALL_ID = 'SET_HALL_ID'
export const SET_HALL_CONTENTS = 'SET_HALL_CONTENTS'
export const SET_CURRENT_TICKET_ID = 'SET_CURRENT_TICKET_ID'
export const SET_FILM_CURRENT_SEL_ID = 'SET_FILM_CURRENT_SEL_ID'
export const SAVE_ALL_FILM_DATA = 'SAVE_ALL_FILM_DATA'
export const SAVE_ALL_TIME_DATA = 'SAVE_ALL_TIME_DATA'
export const SAVE_ALL_HALL_DATA = 'SAVE_ALL_HALL_DATA'
export const SET_CURRENT_FILM_TITLE = 'SET_CURRENT_FILM_TITLE'
export const CHECK_OUT_COUPON_RESULT = 'CHECK_OUT_COUPON_RESULT'
export const SAVE_CURRENT_PLAN_SEAT = 'SAVE_CURRENT_PLAN_SEAT'
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE'
export const PAY_METHOD_TRIGER = 'PAY_METHOD_TRIGER'
export const GET_KIND_PRICE = 'GET_KIND_PRICE'
export const GET_CART_BILLCODEUID = 'GET_CART_BILLCODEUID'
export const GET_CART_CINEMAUID = 'GET_CART_CINEMAUID'
export const SAVE_CHANGE_CASH = 'SAVE_CHANGE_CASH'
export const SET_CURRENT_PLANCODE = 'SET_CURRENT_PLANCODE'
export const SET_RETURN_PAY = 'SET_RETURN_PAY'
export const SET_PAY_RESULT = 'SET_PAY_RESULT'
export const RENDER_SELECTION = 'RENDER_SELECTION'
export const RENDER_SELECTION_AFTER_RELEASE = 'RENDER_SELECTION_AFTER_RELEASE'
export const CHECK_CURRENT_SEAT_STATUS = 'CHECK_CURRENT_SEAT_STATUS'
export const SAVE_USER_INFO = 'SAVE_USER_INFO'
export const SAVE_CINEMA_INFO = 'SAVE_CINEMA_INFO'
export const CHANGE_TICKETS_TRIGER = 'CHANGE_TICKETS_TRIGER'
export const SAVE_CHANGE_CODE = 'SAVE_CHANGE_CODE'

//购物车
export const GET_CART_BILLCODE = 'GET_CART_BILLCODE' // 订单编号
export const GET_CART_DATA = 'GET_CART_DATA' //电影票
export const GET_CART_GOODSLIST = 'GET_CART_GOODSLIST'
export const SET_CART_NUMBER = 'SET_CART_NUMBER'
export const SHOW_CART_KEYBOARD = 'SHOW_CART_KEYBOARD'
export const CART_SET_GOODS_DATA = 'CART_SET_GOODS_DATA'//卖品


//设置
export const SET_CONFIG_DATA = 'SET_CONFIG_DATA' // 设置全部数据
export const SET_FILM_PRINT = 'SET_FILM_PRINT' // 电影打印机
export const SET_BILL_PRINT = 'SET_BILL_PRINT' //小票打印机
export const SET_COUPON_PRINT = 'SET_COUPON_PRINT' //票券打印机
export const SET_CASH_BOX = 'SET_CASH_BOX' //钱箱
export const SET_CARD_READER = 'SET_CARD_READER' //读卡器
export const SET_KEYBOARD = 'SET_KEYBOARD' //密码键盘
export const SET_FILM_PRINT_OFFSET = 'SET_FILM_PRINT_OFFSET' //影票打印机偏移坐标
export const SET_COUNTER_TYPE = 'SET_COUNTER_TYPE' //终端售卖商品范围


//授权
export const EMPOWER_SET_SHOW = 'EMPOWER_SET_SHOW'
export const EMPOWER_SET_TYPE = 'EMPOWER_SET_TYPE'
export const EMPOWER_SET_USER = 'EMPOWER_SET_USER'
export const EMPOWER_SET_PASSWORD = 'EMPOWER_SET_PASSWORD'

