// 前端字典 整体文件
var feDicts = [{
  'code': 'resource_sys_code',
  'dictItems': [{
      'id': 27,
      'code': 'CRM',
      'name': '会员',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 28,
      'code': 'CTM',
      'name': '票务',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 29,
      'code': 'CCM',
      'name': '票券',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 30,
      'code': 'RPT',
      'name': '报表',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 31,
      'code': 'CMM',
      'name': '营销',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 32,
      'code': 'CAM',
      'name': '经营决策',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 33,
      'code': 'CIM',
      'name': '零售',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 34,
      'code': 'CSM',
      'name': '交易',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 35,
      'code': 'SYSTEM',
      'name': '系统设置',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }, {
      'id': 146,
      'code': 'HWORK',
      'name': '首页工作台',
      'status': 1,
      'mainCode': 'resource_sys_code'
    }]
}, {
  'code': 'orst_consumer_status',
  'dictItems': [{
      'id': 88,
      'code': '1',
      'name': '未启用',
      'status': 1,
      'mainCode': 'orst_consumer_status'
    }, {
      'id': 89,
      'code': '2',
      'name': '启用中',
      'status': 1,
      'mainCode': 'orst_consumer_status'
    }, {
      'id': 90,
      'code': '3',
      'name': '已启用',
      'status': 1,
      'mainCode': 'orst_consumer_status'
    }, {
      'id': 91,
      'code': '4',
      'name': '已禁用',
      'status': 1,
      'mainCode': 'orst_consumer_status'
    }]
}, {
  'code': 'orst_consumer_consumer_type',
  'dictItems': [{
      'id': 36,
      'code': '1',
      'name': '影管',
      'status': 1,
      'mainCode': 'orst_consumer_consumer_type'
    }, {
      'id': 37,
      'code': '2',
      'name': '院线',
      'status': 1,
      'mainCode': 'orst_consumer_consumer_type'
    }, {
      'id': 38,
      'code': '3',
      'name': '发行',
      'status': 1,
      'mainCode': 'orst_consumer_consumer_type'
    }, {
      'id': 39,
      'code': '4',
      'name': '零售',
      'status': 1,
      'mainCode': 'orst_consumer_consumer_type'
    }]
}, {
  'code': 'orst_consumer_resource_type',
  'dictItems': [{
      'id': 40,
      'code': '1',
      'name': '独享',
      'status': 1,
      'mainCode': 'orst_consumer_resource_type'
    }, {
      'id': 41,
      'code': '2',
      'name': '共享',
      'status': 1,
      'mainCode': 'orst_consumer_resource_type'
    }]
}, {
  'code': 'orst_product_product_type',
  'dictItems': [{
      'id': 47,
      'code': '1',
      'name': '管理后台',
      'status': 1,
      'mainCode': 'orst_product_product_type'
    }, {
      'id': 48,
      'code': '2',
      'name': 'POS柜台',
      'status': 1,
      'mainCode': 'orst_product_product_type'
    }, {
      'id': 49,
      'code': '3',
      'name': '移动端',
      'status': 1,
      'mainCode': 'orst_product_product_type'
    }]
}, {
  'code': 'orst_item_attribute_attribute_type',
  'dictItems': [{
      'id': 50,
      'code': '1',
      'name': '关键属性',
      'status': 1,
      'mainCode': 'orst_item_attribute_attribute_type'
    }, {
      'id': 51,
      'code': '2',
      'name': '销售属性',
      'status': 1,
      'mainCode': 'orst_item_attribute_attribute_type'
    }, {
      'id': 52,
      'code': '3',
      'name': '扩展属性',
      'status': 1,
      'mainCode': 'orst_item_attribute_attribute_type'
    }]
}, {
  'code': 'orst_item_attribute_input_type',
  'dictItems': [{
      'id': 53,
      'code': '1',
      'name': '单选',
      'status': 1,
      'mainCode': 'orst_item_attribute_input_type'
    }, {
      'id': 54,
      'code': '2',
      'name': '多选',
      'status': 1,
      'mainCode': 'orst_item_attribute_input_type'
    }, {
      'id': 55,
      'code': '3',
      'name': '输入',
      'status': 1,
      'mainCode': 'orst_item_attribute_input_type'
    }]
}, {
  'code': 'movie_film_film_type',
  'dictItems': [{
      'id': 56,
      'code': '1',
      'name': '爱情',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 57,
      'code': '2',
      'name': '喜剧',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 58,
      'code': '3',
      'name': '动画',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 59,
      'code': '4',
      'name': '剧情',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 60,
      'code': '5',
      'name': '恐怖',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 61,
      'code': '6',
      'name': '惊悚',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 62,
      'code': '7',
      'name': '科幻',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 63,
      'code': '8',
      'name': '动作',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 64,
      'code': '9',
      'name': '悬疑',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 65,
      'code': '10',
      'name': '犯罪',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 66,
      'code': '11',
      'name': '冒险',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 67,
      'code': '12',
      'name': '战争',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 68,
      'code': '13',
      'name': '奇幻',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 69,
      'code': '14',
      'name': '运动',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 70,
      'code': '15',
      'name': '家庭',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 71,
      'code': '16',
      'name': '古装',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 72,
      'code': '17',
      'name': '武侠',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 73,
      'code': '18',
      'name': '西部',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 74,
      'code': '19',
      'name': '历史',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 75,
      'code': '20',
      'name': '传记',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 76,
      'code': '21',
      'name': '歌舞',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 77,
      'code': '22',
      'name': '黑色电影',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 78,
      'code': '23',
      'name': '短片',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 79,
      'code': '24',
      'name': '纪录',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 80,
      'code': '25',
      'name': '魔幻',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 81,
      'code': '26',
      'name': '伦理',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 82,
      'code': '27',
      'name': '文艺',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 83,
      'code': '28',
      'name': '灾难',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }, {
      'id': 266,
      'code': '29',
      'name': '其他',
      'status': 1,
      'mainCode': 'movie_film_film_type'
    }]
}, {
  'code': 'base_pay_mode_pay_type',
  'dictItems': [{
      'id': 315,
      'code': '1',
      'name': '第三方',
      'status': 1,
      'mainCode': 'base_pay_mode_pay_type'
    }, {
      'id': 316,
      'code': '2',
      'name': '网银',
      'status': 1,
      'mainCode': 'base_pay_mode_pay_type'
    }, {
      'id': 317,
      'code': '3',
      'name': '自定义',
      'status': 1,
      'mainCode': 'base_pay_mode_pay_type'
    }]
}, {
  'code': 'movie_film_frame_number',
  'dictItems': [{
      'id': 95,
      'code': '24',
      'name': '24帧',
      'status': 1,
      'mainCode': 'movie_film_frame_number'
    }, {
      'id': 96,
      'code': '48',
      'name': '48帧',
      'status': 1,
      'mainCode': 'movie_film_frame_number'
    }, {
      'id': 97,
      'code': '120',
      'name': '120帧',
      'status': 1,
      'mainCode': 'movie_film_frame_number'
    }]
}, {
  'code': 'movie_film_film_subtitles',
  'dictItems': [{
      'id': 101,
      'code': '0',
      'name': '中文',
      'status': 1,
      'mainCode': 'movie_film_film_subtitles'
    }, {
      'id': 102,
      'code': '1',
      'name': '英文',
      'status': 1,
      'mainCode': 'movie_film_film_subtitles'
    }, {
      'id': 103,
      'code': '2',
      'name': '中英双语',
      'status': 1,
      'mainCode': 'movie_film_film_subtitles'
    }]
}, {
  'code': 'movie_film_film_level',
  'dictItems': [{
      'id': 104,
      'code': 'A',
      'name': 'A级',
      'status': 1,
      'mainCode': 'movie_film_film_level'
    }, {
      'id': 105,
      'code': 'B',
      'name': 'B级',
      'status': 1,
      'mainCode': 'movie_film_film_level'
    }, {
      'id': 106,
      'code': 'C',
      'name': 'C级',
      'status': 1,
      'mainCode': 'movie_film_film_level'
    }, {
      'id': 145,
      'code': 'S',
      'name': 'S级',
      'status': 1,
      'mainCode': 'movie_film_film_level'
    }]
}, {
  'code': 'movie_film_producing_area',
  'dictItems': [{
      'id': 107,
      'code': 'CN',
      'name': '中国',
      'status': 1,
      'mainCode': 'movie_film_producing_area'
    }, {
      'id': 108,
      'code': 'US',
      'name': '美国',
      'status': 1,
      'mainCode': 'movie_film_producing_area'
    }, {
      'id': 109,
      'code': 'IN',
      'name': '印度',
      'status': 1,
      'mainCode': 'movie_film_producing_area'
    }]
}, {
  'code': 'movie_film_film_language',
  'dictItems': [{
      'id': 110,
      'code': 'CN',
      'name': '国语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 111,
      'code': 'EN',
      'name': '英语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 112,
      'code': 'HK',
      'name': '粤语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 113,
      'code': 'GM',
      'name': '德语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 114,
      'code': 'JP',
      'name': '日语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 115,
      'code': 'KO',
      'name': '韩语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 116,
      'code': 'FR',
      'name': '法语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 117,
      'code': 'RS',
      'name': '俄语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 118,
      'code': 'MN',
      'name': '蒙语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 119,
      'code': 'SE',
      'name': '瑞典',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 120,
      'code': 'TI',
      'name': '藏语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 121,
      'code': 'TY',
      'name': '泰语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 122,
      'code': 'DM',
      'name': '丹麦语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 123,
      'code': 'KL',
      'name': '科隆语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 124,
      'code': 'YD',
      'name': '印度语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 125,
      'code': 'ES',
      'name': '西班牙语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 126,
      'code': 'IT',
      'name': '意大利语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 127,
      'code': 'PTY',
      'name': '葡萄牙语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 128,
      'code': 'LST',
      'name': '莱索托语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 129,
      'code': 'ML',
      'name': '马来语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 130,
      'code': 'MNY',
      'name': '闽南语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 131,
      'code': 'TUR',
      'name': '土耳其语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 132,
      'code': 'SC',
      'name': '四川话',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 133,
      'code': 'HN',
      'name': '湖南话',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 134,
      'code': 'SX',
      'name': '陕西话',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 135,
      'code': 'HE',
      'name': '河南话',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 136,
      'code': 'ALB',
      'name': '阿拉伯语',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 137,
      'code': 'YY',
      'name': '原音',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }, {
      'id': 138,
      'code': 'WU',
      'name': '默片',
      'status': 1,
      'mainCode': 'movie_film_film_language'
    }]
}, {
  'code': 'movie_film_film_edition',
  'dictItems': [{
      'id': 304,
      'code': '0',
      'name': '观摩影片',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 305,
      'code': '1',
      'name': '数字2D',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 306,
      'code': '2',
      'name': '数字3D',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 307,
      'code': '3',
      'name': 'IMAX2D',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 308,
      'code': '4',
      'name': 'IMAX3D',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 309,
      'code': '5',
      'name': '胶片(进口)',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 300,
      'code': '6',
      'name': '其他特种电影',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 301,
      'code': '7',
      'name': '其他',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 302,
      'code': '8',
      'name': '中国巨幕2D',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }, {
      'id': 303,
      'code': '9',
      'name': '中国巨幕3D',
      'status': 1,
      'mainCode': 'movie_film_film_edition'
    }]
}, {
  'code': '3355',
  'dictItems': [{
      'id': 329,
      'code': '11112222',
      'name': '222222',
      'status': 1,
      'mainCode': '3355'
    }, {
      'id': 330,
      'code': '13241554123',
      'name': '1342315',
      'status': 1,
      'mainCode': '3355'
    }]
}];

export default feDicts;
